import asyncio
import os
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from mcp_use import MCPAgent, MCPClient

async def run_mcp_agent_query(agent: MCPAgent, message: str) -> str:
    """
    Runs a query using a pre-initialized MCP Agent.

    Args:
        agent: The initialized MCPAgent instance.
        message: The text message query.

    Returns:
        The raw response generated by the MCP agent.
        Raises exceptions on failure.
    """
    print(f"Running MCP Agent with query: '{message}'")
    # Assume agent and its client/sessions are managed externally
    agent_result = await agent.run(message, max_steps=10) # Use pre-initialized agent
    print(f"MCP Agent Raw Result: {agent_result}")
    return agent_result

# Removed old process_whatsapp_message which created client/agent each time
# Removed __main__ block



